[build]
functions = "netlify/functions"
publish = "dist"

[dev]
functions = "netlify/functions"
publish = "dist"
port = 8888

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
